name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb989475a48776a63e788798187759b14ffbef142c8bdde547e9a7f233379af3"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
