name = "Pseudoscience Modpack Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "187eb03b2fb576438d3ab6130fcd94eaa7dfb2f4f2a050ea75015fabf7eaf042"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
