name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b3c3d37fa6e42b8c9ed5c18ad63c4c22fac7f57233d1f746876ce160eedbea08"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
