name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2d3b9baade99f0ca1a01392a440fbe56df51d876e696380efe364ec73c6d4e2d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
