name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6a2f7d2a0479c96491cf9ba4ca58ee4ef5603a7c6cb98d1669118918deb13987"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
