name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8113388f3026b04ef54b1f3a189ad80176a96a0e0363934147259bdb10fe2c50"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
