name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6d454818360924b3afa2a39d5af010a7859a2a4442bbbd4cc3231eff8fb241e0"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
