name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58de5e0e1c924bd0bfcdfa4d7674406b6c4501a6c8ff4442ecfa224795832d75"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
