name = "Pseudoscience Modpack Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5e38de63e8450c41ca266c60fe3efa50a8a6d0653182bbd7539528be10360ef4"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
