name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f527bfc227885790597dfd4ed75d185c90f2ecca6fff1846e6cf27d6df0a3e1"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
