name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5446ce860a4da091575f356588fd5456f0160991bd74a2ad34fb7621162c977c"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
