name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b73c7230ab2a335f7e018de40f5bbdd6ae30e255f5b626a20072d795f12f11f7"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
