name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb6437d1c0b747bb991a34f86d1139c9ab786060bb0e8f1c7b2e66149c63797a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
