name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab715c478bb4c5251cb4afdf25db0f650386ea0e8194534969c5fbc2b3f5e8b8"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
