name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35fc7be0381c1e47c8ee6ffbccae5b90459d9a64aada6e4e624c890841b8a39a"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
