name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6618580fd8ab2781f98614162997f723ea3915f6af22ca2c1046fbe881f49f60"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
