name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd6a0b4f0c8f7d5e05f321d76a8a411c5a38fc2cf10142d9152ab6fdd091dab5"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
