name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6936f892f7ab4d00b168ed38ef86d62a5f12a803aa196f60f7b0013488d0408d"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
