name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "233f9654e3d8f0d5fa3b49773fe799c60ebb9da46f48e9a6397a53f816ac3dbb"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
