name = "Pseudoscience Modpack Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6a2c40d26a83d4b401d3f3be333af10d8c49115d75c166af16f712fe4ab7fe8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.1"
