name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cee124c21fa0af6cafea13b56544bd382e7c827c14791989a8b509ddfd685022"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
