name = "Pseudoscience: Iteration II"
author = "oskardotglobal, emorydeer2"
version = "2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f5d5d7ebf0d688df13415048da5e702fc5917d372c9f9cb37fb70ba7eb1af869"

[versions]
fabric = "0.16.9"
minecraft = "1.20.1"
