# Adds NBT 'authors' when creating a new filled map
copyright: true

# Works if 'copyright' is/was 'true'. Up to 5 players can be displayed in a map lore
displayAuthorsLore: true

# Nobody can make a copy of a map (except authors if 'authorsCanCopy' is 'true')
disableCopy: false

# Works if 'copyright' is/was 'true'
authorsCanCopy: true

# Authors can use `/mapAuthor add <player>` command
authorsCanAddAuthors: true

# Allows to clean a map with a bucket of water in a cartography table
cleanMap: false
